#!/bin/sh

sysresources=/etc/X11/xinit/.Xresources
userresources=$DOTFILES_PATH/linux/misc.ad
askpassresources=$DOTFILES_PATH/linux/x11-askpass.ad

# merge in defaults and keymaps
[ -f "$sysresources" ] && xrdb -merge "$sysresources"
unset sysresources

# loads terminal color scheme
[ -f "$userresources" ] && xrdb -merge "$userresources"
unset userresources

[ -f "$askpassresources" ] && xrdb -merge "$askpassresources"
unset askpassresources

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# decrease delay for key autorepeat
xset r rate 300 50

# Lock autimatically before hibernate/suspend
xss-lock --transfer-sleep-lock -- lock-screen.sh &

# Provides window transparancy
picom -b

redshift -l 50.45:30.523333 &

# Set charge thresholds between 40%-80%
sudo tlp setcharge 40 80 BAT0

set-wallpaper.sh

# load bindings
sxhkd &

# starting it here to ensure it will be stopped within bspwm
statusline-start.sh 2>>$STATUSLINE_LOG &
exec bspwm
# vim:ft=sh
