#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

bspc desktop -f 1

bspc config border_width                2
bspc config window_gap                  12
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config pointer_follows_monitor     true

# use Alt for moving (left mouse button)
# and resizing (right mouse button)
bspc config pointer_modifier            mod1

bspc rule -a mpv state=floating
bspc rule -a Zathura state=tiled
bspc rule -a ShowCal state=floating rectangle=210x500+1690+35

# get rid of cross cursor above wallpaper:
xsetroot -cursor_name left_ptr &

bspc config urgent_border_color "#72003e"
bspc config normal_border_color "#586e75"
# bspc config active_border_color "$color2"
bspc config focused_border_color "#268bd2"
# bspc config presel_border_color "$color1"

# Set default monitor depending on what is plugged in
toggle-screens.sh --init &
