#!/usr/bin/env bash

shopt -s nullglob globstar

action=${1-show}

typeit=0
if [[ $2 == "--type" ]]; then
        typeit=1
        shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}

if [ "${action}" = "show" ]; then
  password_files=( "$prefix"/**/*.gpg )
else
  password_files=( "$prefix"/otp/**/*.gpg )
fi

password_files=( "${password_files[@]#"$prefix"/}" )

if [ "${action}" = "show" ]; then
  password_files=( ${password_files[@]//otp*/} )
fi

password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu)

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
  pass $action -c "$password" 2>/dev/null
else
  pass $action "$password" | { IFS= read -r pass; printf %s "$pass"; } |
    xdotool type --clearmodifiers --file -
fi
