#!/bin/bash

# super useful for TDD

# to run app on every change use:
# find src | entr -s -c 'cargo run'

while true; do
  rg --files src | entr -c -d cargo test $@

  # allows break infinite loop
  if [ "$?" = 130 ]; then
    echo "Interrupted by user (C-c or q)"
    exit 0
  fi
done

