#!/bin/bash

# remove cargo command name argument if present
all_args="$@"
if [ "$all_args" = "test-watch" ]; then
  # running as cargo command
  rest_args=""
elif [ "$1" = "test-watch" ]; then
  rest_args="${all_args#test-watch }"
else
  # keep all arguments
  rest_args="${all_args}"
fi

# super useful for TDD
rg --files src | entr -c cargo test $rest_args
