#!/bin/bash

CONFIGS_BIN_DIR=$(dirname "$0")

print_step_result() {
  local command_res=$1
  if [ "${command_res}" = "0" ]; then
    echo "DONE"
  else
    echo "FAIL"
  fi
}

sync_git_repo() {
  local repo_path=$1

  cd "${repo_path}"

  # check if repo is clean
  if [ "$(git status -s | wc -l)" = "0" ]; then
    git pull > /dev/null \
      && git push &> /dev/null
    print_step_result "$?"
  else
    echo "FAIL: uncommited changes"
  fi

  cd ${CONFIGS_BIN_DIR}
}

# this ensures we have access to configs-link
# whatever PATH we have
cd ${CONFIGS_BIN_DIR}

echo "Syncing configs:"

printf " * unlink all...        "
if [ "$1" = "--relink" ] && [ "${CONFIGS_DEBUG}" != "true" ]; then
  ./configs-link unlink > /dev/null
  print_step_result "$?"
else
  echo "SKIP"
fi

printf " * dotfiles...          "
sync_git_repo "${DOTFILES_PATH}"

printf " * private dotfiles...  "
sync_git_repo "${DOTFILES_PATH}/private"

printf " * password store...    "
sync_git_repo "${HOME}/.password-store"

printf " * link all...          "
if [ "$1" = "--relink" ] && [ "${CONFIGS_DEBUG}" != "true" ]; then
  ./configs-link > /dev/null
  print_step_result "$?"
else
  echo "SKIP"
fi

echo "Update completed."
