#!/bin/bash

CONFIGS_BIN_DIR=$(dirname "$0")

echo " = Updating configs = "
pushd ${CONFIGS_BIN_DIR}

echo "Unlink old configs"
[[ "${CONFIGS_DEBUG}" != "true" ]] && ./configs-link unlink

echo "Updating configs repo"
if [ "${CONFIGS_DEBUG}" != "true" ]; then
  git pull
  PRIVATE_CONFIGS_DIR=${DOTFILES_PATH}/private/.git
  if [ -d "${PRIVATE_CONFIGS_DIR}" ]; then
    git --git-dir="${PRIVATE_CONFIGS_DIR}" pull
  fi
fi

echo "Link new configs"
[[ "${CONFIGS_DEBUG}" != "true" ]] && ./configs-link

echo " = Update finished! = "
popd
